package component:usb@0.1.0;

interface events {
    use device.{usb-device};

    variant device-connection-event {
        pending,
        closed,
        connected(usb-device),
        disconnected(usb-device)
    }

    update: func() -> device-connection-event;
}
