package component:usb@0.1.0;

interface types {
    record properties {
        device-class: u8
    }
}

interface device {
    use types.{properties};

    resource usb-device {
        //constructor(init: list<u8>);
        
        properties: func() -> properties;
        
    }
    
    get-devices: func() -> list<usb-device>;
}

/// An example world for the component to target.
world usb {
    import device;
    export device;
    export types;
}
